name: CI/CD Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kodu
        uses: actions/checkout@v4

      - name: Logowanie do Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Logowanie do Azure Container Registry
        run: az acr login --name szopapka-acr

      - name: Budowanie i pushowanie obrazu Dockera
        run: |
          docker build -t szopapka-acr.azurecr.io/frontend:latest .
          docker push szopapka-acr.azurecr.io/frontend:latest

      - name: Aktualizacja ACA
        run: az containerapp update \
          --name frontend \
          --resource-group szopapka-rg \
          --image szopapka-acr.azurecr.io/frontend:latest
